package com.epiforum.server.data.entity;

// Generated Mar 20, 2014 8:33:43 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.epiforum.server.data.listener.ICreateListener;
import com.epiforum.server.data.listener.IUpdateListener;

/**
 * Board generated by hbm2java
 */
@Entity
@Cacheable
@Table(name = "board")
public class Board implements Serializable, ICreateListener, IUpdateListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2578757668147679579L;

	private Integer			id;
	private Date			created;
	private Date			modified;
	private Category		category;
	private String			title;
	private String			description;

	private List<Topic>		topics = new ArrayList<Topic>(0);

	public 					Board() {
	}

	public 					Board(Category category, Date created, Date modified, String title) {
		this.category = category;
		this.created = created;
		this.modified = modified;
		this.title = title;
	}

	public 					Board(Category category, Date created, Date modified, String title,
			String description, List<Topic> topics) {
		this.category = category;
		this.created = created;
		this.modified = modified;
		this.title = title;
		this.description = description;
		this.topics = topics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer			getId() {
		return this.id;
	}

	public void				setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId", nullable = false)
	public Category			getCategory() {
		return this.category;
	}

	public void				setCategory(Category category) {
		this.category = category;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date				getCreated() {
		return this.created;
	}

	public void				setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", nullable = false, length = 19)
	public Date				getModified() {
		return this.modified;
	}

	public void				setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String			getTitle() {
		return this.title;
	}

	public void				setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 256)
	public String			getDescription() {
		return this.description;
	}

	public void				setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "board")
	public List<Topic>		getTopics() {
		return this.topics;
	}

	public void				setTopics(List<Topic> topics) {
		this.topics = topics;
	}
}
