package com.epiforum.server.data.entity;
// default package
// Generated Mar 21, 2014 1:23:34 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.epiforum.server.data.listener.ICreateListener;
import com.epiforum.server.data.listener.IUpdateListener;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", uniqueConstraints = @UniqueConstraint(columnNames = "nickname"))
@NamedQueries({
	@NamedQuery(
			name = "Profile.getProfileFromNickname",
			query = "SELECT pro FROM Profile pro WHERE pro.nickname = :nickname")
})
public class Profile implements Serializable, ICreateListener, IUpdateListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1760141895956098813L;

	private Integer			id;
	private Date			created;
	private Date			modified;
	private Account			account;
	private String			firstname;
	private String			lastname;
	private String			nickname;
	private String			phone;
	private String			facebookPage;
	private String			twitterPage;
	private String			skypeContact;
	private String			city;
	private String			description;
	private String			signature;
	private Boolean			gender;
	private Date			birthdate;
	private Integer			nbPost;
	private Integer			nbThank;

	private List<Post>		posts = new ArrayList<Post>(0);
	private List<Session>	sessions = new ArrayList<Session>(0);

	public 					Profile() {
		super();
	}

	public 					Profile(Account account, String nickname) {
		this.account = account;
		this.nickname = nickname;
		this.nbPost = 0;
		this.nbThank = 0;
	}

	public 					Profile(Account account,	String firstname, String lastname, String nickname, String phone,
			String facebookPage, String twitterPage, String skypeContact, String city, String description, String signature,
			Boolean gender, Date birthdate) {
		this.account = account;
		this.firstname = firstname;
		this.lastname = lastname;
		this.nickname = nickname;
		this.phone = phone;
		this.facebookPage = facebookPage;
		this.twitterPage = twitterPage;
		this.skypeContact = skypeContact;
		this.city = city;
		this.description = description;
		this.signature = signature;
		this.gender = gender;
		this.birthdate = birthdate;
		this.nbPost = 0;
		this.nbThank = 0;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer			getId() {
		return this.id;
	}

	public void				setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountId", nullable = false)
	public Account			getAccount() {
		return this.account;
	}

	public void				setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date				getCreated() {
		return this.created;
	}

	public void				setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", nullable = false, length = 19)
	public Date				getModified() {
		return this.modified;
	}

	public void				setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "firstname", length = 64)
	public String			getFirstname() {
		return this.firstname;
	}

	public void				setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 64)
	public String			getLastname() {
		return this.lastname;
	}

	public void				setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "nickname", unique = true, nullable = false, length = 128)
	public String			getNickname() {
		return this.nickname;
	}

	public void				setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "phone", length = 16)
	public String			getPhone() {
		return this.phone;
	}

	public void				setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "facebookPage", length = 64)
	public String			getFacebookPage() {
		return this.facebookPage;
	}

	public void				setFacebookPage(String facebookPage) {
		this.facebookPage = facebookPage;
	}

	@Column(name = "twitterPage", length = 64)
	public String			getTwitterPage() {
		return this.twitterPage;
	}

	public void				setTwitterPage(String twitterPage) {
		this.twitterPage = twitterPage;
	}

	@Column(name = "skypeContact", length = 64)
	public String			getSkypeContact() {
		return this.skypeContact;
	}

	public void				setSkypeContact(String skypeContact) {
		this.skypeContact = skypeContact;
	}

	@Column(name = "city", length = 128)
	public String			getCity() {
		return this.city;
	}

	public void				setCity(String city) {
		this.city = city;
	}

	@Column(name = "description", length = 256)
	public String			getDescription() {
		return this.description;
	}

	public void				setDescription(String description) {
		this.description = description;
	}

	@Column(name = "signature", length = 256)
	public String			getSignature() {
		return this.signature;
	}

	public void				setSignature(String signature) {
		this.signature = signature;
	}

	@Column(name = "gender", columnDefinition = "BIT")
	public Boolean			getGender() {
		return this.gender;
	}

	public void				setGender(Boolean gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 10)
	public Date				getBirthdate() {
		return this.birthdate;
	}

	public void				setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "posts", nullable = false)
	public Integer			getNbPosts() {
		return this.nbPost;
	}

	public void				setNbPosts(Integer posts) {
		this.nbPost = posts;
	}

	@Column(name = "thanks", nullable = false)
	public Integer			getThanks() {
		return this.nbThank;
	}

	public void				setThanks(Integer thanks) {
		this.nbThank = thanks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public List<Post>		getPosts() {
		return this.posts;
	}

	public void				setPosts(List<Post> posts) {
		this.posts = posts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public List<Session>	getSessions() {
		return this.sessions;
	}

	public void				setSessions(List<Session> sessions) {
		this.sessions = sessions;
	}
	
	public Integer			addNbThank() {
		this.nbThank +=1;
		return this.nbThank;
	}
	
	public Integer			addNbPost() {
		this.nbPost +=1;
		return this.nbPost;
	}
}